        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 31 19:35:38 2016
        MODULE WRITE_LOGFILE__genmod
          INTERFACE 
            SUBROUTINE WRITE_LOGFILE
            END SUBROUTINE WRITE_LOGFILE
          END INTERFACE 
        END MODULE WRITE_LOGFILE__genmod
