        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 31 19:35:38 2016
        MODULE TIMESTAMP__genmod
          INTERFACE 
            SUBROUTINE TIMESTAMP(TIMESTRING)
              CHARACTER(LEN=72), INTENT(OUT) :: TIMESTRING
            END SUBROUTINE TIMESTAMP
          END INTERFACE 
        END MODULE TIMESTAMP__genmod
