        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep  7 16:44:28 2018
        MODULE FFTPACK_RFFTI__genmod
          INTERFACE 
            SUBROUTINE FFTPACK_RFFTI(N,WSAVE)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: WSAVE(2*N+15)
            END SUBROUTINE FFTPACK_RFFTI
          END INTERFACE 
        END MODULE FFTPACK_RFFTI__genmod
