        !COMPILER-GENERATED INTERFACE MODULE: Fri Sep  7 16:44:47 2018
        MODULE QUICKSORT__genmod
          INTERFACE 
            SUBROUTINE QUICKSORT(N,X,IND)
              INTEGER(KIND=4), INTENT(IN) :: N
              REAL(KIND=4), INTENT(IN) :: X(N)
              INTEGER(KIND=4), INTENT(INOUT) :: IND(N)
            END SUBROUTINE QUICKSORT
          END INTERFACE 
        END MODULE QUICKSORT__genmod
