        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep  9 19:34:50 2018
        MODULE TIMESTAMP__genmod
          INTERFACE 
            SUBROUTINE TIMESTAMP(TIMESTRING)
              CHARACTER(LEN=72), INTENT(OUT) :: TIMESTRING
            END SUBROUTINE TIMESTAMP
          END INTERFACE 
        END MODULE TIMESTAMP__genmod
