        !COMPILER-GENERATED INTERFACE MODULE: Sun Sep  9 19:34:50 2018
        MODULE WRITE_LOGFILE__genmod
          INTERFACE 
            SUBROUTINE WRITE_LOGFILE
            END SUBROUTINE WRITE_LOGFILE
          END INTERFACE 
        END MODULE WRITE_LOGFILE__genmod
