#!/bin/csh -f

if ( ! -e configure.gsi ) then
	echo "Do 'configure' first"
	exit ( 1 ) 
endif

if      ( ${#argv} == 0 ) then
	set names	=	( lib gsi )
	set NAMES	=	( LIB GSI )
else
        echo "*****"
        echo " "
	echo "Unrecognized compile target $1."
        echo " "
        echo " or just run compile with no target to build everything."
        echo " "
        echo "*****"
        exit(1)
endif

echo " "
if ( ${#argv} == 0 ) then
	echo "**** Compiling GSI and all libs ****"
else
	echo "**** No arguments are needed... Compiling GSI and all libs ****"
endif

echo " "
echo " "
echo " ----------------------- "
echo " Modules Loaded "
echo " "
if ( `echo $HOSTNAME | cut -c1-2` == ys ) then
  /glade/apps/opt/lmod/lmod/libexec/lmod sh list
else if ( `echo $REMOTEHOST | cut -c1-5` == "theia" ) then
  /apps/lmod/lmod/libexec/lmod csh list
else if ( `echo $REMOTEHOST | cut -c1-11` == "bastion-jet" ) then
  /apps/lmod/lmod/libexec/lmod csh list
endif
echo " "
echo " ----------------------- "
echo " SVN INFO "
svn info
echo " "
echo " ----------------------- "
#
#
mkdir -p ./lib
mkdir -p ./include

( make -i -f makefile_DTC all )

exit(0)
