# Module dependencies
nemsio_module.o: nemsio_openclose.o nemsio_read.o nemsio_write.o
nemsio_module.lo: nemsio_openclose.lo nemsio_read.lo nemsio_write.lo
nemsio_module.obj: nemsio_openclose.obj nemsio_read.obj nemsio_write.obj
nemsio_read.o: nemsio_openclose.o
nemsio_read.lo: nemsio_openclose.lo
nemsio_read.obj: nemsio_openclose.obj
nemsio_write.o: nemsio_openclose.o
nemsio_write.lo: nemsio_openclose.lo
nemsio_write.obj: nemsio_openclose.obj
