#!/bin/ksh --login
# 
# A utility to get the required files from HPSS to run a standalone GSI job.
# This is loosely based on R. Treadon's hpssget_gdas.sh
# This script is designed to be run interactively but can be incorporated into 
# other scripts to be run in batch if desired.
#
# One argument, the desired analysis date, is required.
# By default the output goes to  /ptmp/${USER}/data_sigmap/globalprod.${adate}
#

if [ $# -eq 1 ]; then 
  adate=$1
else
  echo Incorrect number of arguments.  Usage:
  echo "  Get_Initial_Files <analysis date>"
  exit 1
fi

set -ax

machine="Theia"
#machine="WCOSS"

if [[ "$machine" = "Theia" ]]; then
   nwprod=/scratch4/NCEPDEV/da/save/Michael.Lueken/nwprod 
   ptmp=/scratch4/NCEPDEV/stmp3
   noscrub=/scratch4/NCEPDEV/da/noscrub
   stmp=/scratch4/NCEPDEV/stmp4
   ndate=/scratch4/NCEPDEV/da/save/Michael.Lueken/nwprod/util/exec/ndate 
elif [[ "$machine" = "WCOSS" ]]; then
   nwprod=/nwprod
   ptmp=/ptmp
   stmp=/stmp
   ndate=$nwprod/util/exec/ndate 
fi

# We are getting files for a single analysis date.  Some will come from the previous cycle ($gdate).
incr=06
gdate=`$ndate -${incr} $adate`

# Specify temporary directory (tmpdir) in which to run script.
# Specify directory in which to store retrieved files (savdir)
uname=`whoami`
exp=globalprod.$adate

#tmpdir=/stmp/${uname}/get_initial_files.${adate}
#savdir=/ptmp/${USER}/data_sigmap/${exp}
tmpdir=$stmp/${uname}/get_initial_files.${adate}
savdir=$ptmp/${USER}/data_sigmap/${exp}
#savdir=${noscrub}/${USER}/data_sigmap/${exp}

# Specify name of files to retrieve from this cycle
DFILESA="$DFILESA atmges atmgm1 atmgm2 atmgm3 atmgp1 atmgp2 atmgp3 prepbufr"
DFILESO="$DFILESO 1bamua.tm00.bufr_d 1bamub.tm00.bufr_d 1bhrs2.tm00.bufr_d 1bhrs3.tm00.bufr_d"
DFILESO="$DFILESO 1bhrs4.tm00.bufr_d 1bmhs.tm00.bufr_d 1bmsu.tm00.bufr_d esamua.tm00.bufr_d"
DFILESO="$DFILESO esamub.tm00.bufr_d eshrs3.tm00.bufr_d airsev.tm00.bufr_d mtiasi.tm00.bufr_d"
DFILESO="$DFILESO cris.tm00.bufr_d"
DFILESO="$DFILESO goesfv.tm00.bufr_d gpsro.tm00.bufr_d osbuv8.tm00.bufr_d  sptrmm.tm00.bufr_d"
#DFILESA="$DFILESA ssmit.tm00.bufr_d  spssmi.tm00.bufr_d ssmis.tm00.bufr_d amsre.tm00.bufr_d"
DFILESO="$DFILESO ssmit.tm00.bufr_d  spssmi.tm00.bufr_d ssmisu.tm00.bufr_d amsre.tm00.bufr_d"
DFILESO="$DFILESO gome.tm00.bufr_d omi.tm00.bufr_d syndata.tcvitals.tm00"
DFILESO="$DFILESO atms.tm00.bufr_d"
DFILESO="$DFILESO satwnd.tm00.bufr_d"

# These come from the previous cycle
DFILESB="$DFILESB abias_pc abias_air abias radstat sfcgcy"
DFILESG="$DFILESG sfcf003 sfcf004 sfcf005 sfcf006 sfcf007 sfcf008 sfcf009"
DFILESG="$DFILESG nstf003 nstf004 nstf005 nstf006 nstf007 nstf008 nstf009"


# Make $tmpdir and $savdir.  Change directory to $tmpdir
rm -rf $tmpdir
mkdir -p $tmpdir
cd $tmpdir

mkdir -p $savdir

# SWITCH is the date on which the runhistory tapes moved from 
# hsm to hpss.  The path to the tar files is different for 
# hsm and hpss, hence the need to know when the switch occured.
SWITCH=2003051818

yyyya=`echo $adate | cut -c1-4`
mma=`echo $adate | cut -c5-6`
dda=`echo $adate | cut -c7-8`
hha=`echo $adate | cut -c9-10`

yyyyg=`echo $gdate | cut -c1-4`
mmg=`echo $gdate | cut -c5-6`
ddg=`echo $gdate | cut -c7-8`
hhg=`echo $gdate | cut -c9-10`

#  Based on date in comparison to $SWITCH date, set path to tarfile
if [[ $adate -lt $SWITCH ]]; then
    hpssdira=/hpssuser/g02/wx15gv/s70/hsmprod/runhistory/rh${yyyya}/${yyyya}${mma}/${yyyya}${mma}${dda}
    hpssdirg=/hpssuser/g02/wx15gv/s70/hsmprod/runhistory/rh${yyyyg}/${yyyyg}${mmg}/${yyyyg}${mmg}${ddg}
else
    hpssdira=/NCEPPROD/hpssprod/runhistory/rh${yyyya}/${yyyya}${mma}/${yyyya}${mma}${dda}
    hpssdirg=/NCEPPROD/hpssprod/runhistory/rh${yyyyg}/${yyyyg}${mmg}/${yyyyg}${mmg}${ddg}
fi

tag=gdas
prefixa=./gdas.t${hha}z
prefixg=./gdas.t${hhg}z
#tarfilea=com_gfs_prod_gdas.${adate}.tar  #old
#tarfileg=com_gfs_prod_gdas.${gdate}.tar  #old
tarfilea=gpfs_hps_nco_ops_com_gfs_prod_gdas.${adate}.tar
tarfileg=gpfs_hps_nco_ops_com_gfs_prod_gdas.${gdate}.tar

#     Loop to pull desired files off tape
hpsstar=/nwprod/util/ush/hpsstar
hpsstar=/NCEPPROD/nwprod/util/ush/hpsstar   
if [[ "$machine" = "Theia" ]]; then
   hpsstar=/home/Emily.Liu/bin/hpsstar
  #hpsstar=/scratch4/NCEPDEV/global/save/glopara/nwpara/util/ush/hpsstar
elif [[ "$machine" = "WCOSS" ]]; then
   hpsstar=$nwprod/util/ush/hpsstar
fi

cpy=""
cpn=""
# Files from analysis cycle:
for ft in $DFILESA; do
    fto=${prefixa}.$ft.nemsio
    ftn=$savdir/$fto

    $hpsstar get $hpssdira/$tarfilea $fto
    chmod 644 $fto
    cp $fto $ftn
    
    if [[ $? -eq 0 ]]; then
	cpy="$cpy $ft"
    else
	cpn="$cpn $ft"
    fi
done
for ft in $DFILESO; do
    fto=${prefixa}.$ft
    ftn=$savdir/$fto

    $hpsstar get $hpssdira/$tarfilea $fto
    chmod 644 $fto
    cp $fto $ftn
    
    if [[ $? -eq 0 ]]; then
	cpy="$cpy $ft"
    else
	cpn="$cpn $ft"
    fi
done


# Files from guess cycle
for ft in $DFILESG; do
    fto=${prefixg}.$ft.nemsio
    ftn=$savdir/$fto
  
    $hpsstar get $hpssdirg/$tarfileg $fto
    chmod 644 $fto
    cp $fto $ftn
    
    if [[ $? -eq 0 ]]; then
	cpy="$cpy $ft"
    else
	cpn="$cpn $ft"
    fi
done

for ft in $DFILESB; do
    fto=${prefixg}.$ft
    ftn=$savdir/$fto
  
    $hpsstar get $hpssdirg/$tarfileg $fto
    chmod 644 $fto
    cp $fto $ftn
    
    if [[ $? -eq 0 ]]; then
	cpy="$cpy $ft"
    else
	cpn="$cpn $ft"
    fi
done

echo ${adate}:  File types     copied: $cpy
echo ${adate}:  File types NOT copied: $cpn
echo ${gdate}:  File types     copied: $cpy
echo ${gdate}:  File types NOT copied: $cpn

#Remove temporary directory
cd $tmpdir
rm -rf ./*
cd ../
rm -rf $tmpdir

exit
