#!/bin/ksh
set -x

export RUN_ENVIR=${RUN_ENVIR:-"nco"}
export PS4='$SECONDS + '
date


#############################
# Source relevant config files
#############################
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
configs="base fcst efcs efsoi"
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done


##########################################
# Source machine runtime environment
##########################################
. $HOMEgfs/env/${machine}.env efcs
status=$?
[[ $status -ne 0 ]] && exit $status


##############################################
# Obtain unique process id (pid) and make temp directory
##############################################
export job=${job:-"efsoi.grp${ENSGRP}"}
export pid=${pid:-$$}
export outid=${outid:-"LL$job"}
export jobid=${jobid:-"${outid}.o${pid}"}
if [ $RUN_ENVIR = "nco" ]; then
    export DATA="$DATAROOT/$jobid"
else
    export DATAROOT="$RUNDIR/$CDATE/$CDUMP"
    export DATA="$DATAROOT/$job.grp$ENSGRP"
fi
[[ -d $DATA ]] && rm -rf $DATA
mkdir -p $DATA
cd $DATA


##############################################
# Run setpdy and initialize PDY variables
##############################################
export cycle="t${cyc}z"
setpdy.sh
. ./PDY


##############################################
# Define the Log File directory
##############################################
export jlogfile=${jlogfile:-$COMROOT/logs/jlogfiles/jlogfile.${job}.${pid}}


##############################################
# Determine Job Output Name on System
##############################################
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile


##############################################
# Set variables used in the exglobal script
##############################################
export CDATE=${CDATE:-${PDY}${cyc}}
export CDUMP=${CDUMP:-${RUN:-"gdas"}}
if [ $RUN_ENVIR = "nco" ]; then
    export ROTDIR=${COMROOT:?}/$NET/$envir
fi


##############################################
# Begin JOB SPECIFIC work
##############################################

export CASE=$CASE_ENKF


# Forecast length for EFSOI forecast
export FHMIN=$FHMIN_EFSOI
export FHOUT=$FHOUT_EFSOI
export FHMAX=$FHMAX_EFSOI

# Get EFSOIBEG/EFSOIEND from EFSOIGRP and NMEM_EFSOIGRP
export EFSOIEND=$((NMEM_EFSOIGRP * EFSOIGRP))
export EFSOIBEG=$((EFSOIEND - NMEM_EFSOIGRP + 1))


###############################################################
# Run relevant exglobal script
env
msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"
$LOGSCRIPT


${EFSOIFCSTSH:-$SCRgsi/exglobal_efsoi_fcst_fv3gfs.sh.ecf}
status=$?
[[ $status -ne 0 ]] && exit $status


# Double check the status of members in EFSOIGRP
EFSOIGRP=$ROTDIR/enkf.${CDUMP}.$PDY/$cyc/efsoi.grp${ENSGRP}
npass=0
if [ -f $EFSOIGRP ]; then
    npass=$(grep "PASS" $EFSOIGRP | wc -l)
fi
echo "$npass/$NMEM_EFSOIGRP members successfull in efcs.grp$EFSOIGRP"
if [ $npass -ne $NMEM_EFSOIGRP ]; then
    echo "FATAL ERROR: Failed members in group $EFSOIGRP, ABORT!"
    cat $EFSOIGRP
    exit 99
fi

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
cat $pgmout


msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"


##########################################
# Remove the Temporary working directory
##########################################
cd $DATAROOT
[[ $KEEPDATA = "NO" ]] && rm -rf $DATA

date
exit 0
