# This config file contains the compile options for compilation
# of the GSI code on the NCEP IBM SP.  All production builds
# on NCEP IBM SP are 64-bit

# ----------------------------------
# Redefine variables for NCEP IBM SP
# ----------------------------------
COREINC  = /tg1/projects/wrfruc/mhu/GSI/comGSI/trunk_10/lib/incmod
INCsfcio = $(COREINC)/sfcio_4
INCsigio = $(COREINC)/sigio_4
INCgfsio = $(COREINC)/gfsio_4
INCmpeu  = $(COREINC)/mpeu
##INCcrtm  = $(COREINC)/crtm_gfsgsi

# The below definitions of INCcrtm and LIBcrtm are ONLY
# for pre-implementation compiles.   
#
# When the new global_gsi code is implemented, first implement
# crtm_gfsgsi update.   Next, remove the INCcrtm and LIBcrtm
# lines below.   Uncomment the INCcrtm line above.   Also replace
# "$(LIBcrtm)" on LIBS_N line with "-lcrtm_gfsgsi"

INCcrtm = /tg1/projects/wrfruc/mhu/GSI/comGSI/trunk_10/lib/incmod/crtm_gfsgsi
LIBcrtm = /tg1/projects/wrfruc/mhu/GSI/comGSI/trunk_10/lib/libcrtm_gfsgsi.a

WRFPATH=/whome/mhu/WRFV3x_DFI

LIBwrf          = $(WRFPATH)/main/libwrflib.a
LIBwrfio_int    = $(WRFPATH)/external/io_int/libwrfio_int.a
LIBwrfio_netcdf = $(WRFPATH)/external/io_netcdf/libwrfio_nf.a
INCnetcdf       = $(NETCDF)/include
LIBnetcdf       = -L$(NETCDF)/lib -lnetcdf
OBJwrf_frame_pk = $(WRFPATH)/frame/pack_utils.o
LOADWRF    = $(WRFPATH)/frame/module_internal_header_util.o \
             $(WRFPATH)/frame/pack_utils.o \
             $(WRFPATH)/frame/module_machine.o


WRFLIB = $(LIBwrfio_int) $(LIBwrfio_netcdf) $(LIBnetcdf) $(LOADWRF) $(OBJwrf_frame_pk)

MPITRACE = # /ptmp/mhu/test_Q1FY09/lib/mpi_trace/lib/libmpitrace_smp.a


# Empty out definition of libs use by GMAO GSI building structure
LIBtransf = #-L$(CORELIB) -ltransf
LIBhermes = #-L$(CORELIB) -lhermes
LIBgfio   = #-L$(CORELIB) -lgfio
INChdf    = #-I$(BASEDIR)/$(ARCH)/include/hdf
LIBhdf    = #-L$(BASEDIR)/$(ARCH)/lib  -lmfhdf -ldf -lhdfjpeg -lhdfz -lsz

# ---------------------------
# General targets/definitions
# ---------------------------

  AR     = ar  -v -q

# ----------------------------
# Fortran compiler and options
# ----------------------------

  CF            = mpif90
  FC            = $(CF)

#--- Normal mode options

  PROF= #-g -pg -qfullpath
  OMP = -qsmp=noauto

##  FFLAGS_F90    = -qfree=f90 -qsuffix=f=f90:cpp=F90 -WF,-Dibm_sp,-DWRF
  FFLAGS_F90    = -FR  -O2 -xT -traceback -assume byterecl -DWRF

  FFLAGS_COM_N  = -I ./ -I $(INCmpeu) -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
                  -I $(INCgfsio) -I $(INCnetcdf)  -O3  \

  FFLAGS_N  = $(FFLAGS_F90) $(FFLAGS_COM_N) $(PROF)
  FFLAGS_f  = -qfixed       $(FFLAGS_COM_N) $(PROF)
  FFLAGS    = $(FFLAGS_N) $(PROF)



#--- Debug mode options

  FFLAGS_COM_D  =  -I ./ -I $(INCmpeu) -I $(INCcrtm) -I $(INCsfcio) -I $(INCsigio) \
          -I $(INCgfsio) -I $(INCnetcdf) -qarch=auto \
          -qmaxmem=-1 -qfullpath -qdbg -qstrict -q64 \
          -O0 \
          -qsigtrap=xl__trcedump \
          -qflttrap=overflow:zero:enable \
          -qinitauto=7FF7FFFF \
          -qcheck \
          -qwarn64 \
          -qflag=i:u \
          -qsave \
          -qlistopt \
          -qsource

  FFLAGS_D  = $(FFLAGS_F90) $(FFLAGS_COM_D)



# ----------------------
# C Compiler and options
# ----------------------

  CC            = cc

#--- Normal mode options

  CFLAGS_N      = -I ./ -Dfunder -DFortranByte=char -DFortranInt=int -DFortranLlong='long long'

#--- Debug mode options

  CFLAGS_D      = -I ./ -DFortranByte=char -DFortranInt=int -DFortranLlong='long long' -g


# ------------------
# Linker and options
# ------------------

  LD            = $(CF)

#--- Normal mode options

  LIBS_N        = -L/tg1/projects/wrfruc/mhu/GSI/comGSI/trunk_10/lib -lsp_d -lw3_d -lbufr_d_64 -lbacio_4 \
                  -lsigio_4 -lsfcio_4 -lgfsio_4  $(LIBcrtm) \
                  $(WRFLIB) $(MPITRACE) \
                  -L/opt/intel/mkl/8.1.1/lib/em64t -lmkl_lapack -lmkl_em64t -lguide -lpthread 

  LDFLAGS_N     = ## -lessl_r -lmass -bloadmap:loadmap.txt \
                  -bdatapsize:64K -bstackpsize:64K $(OMP) $(PROF)

  LDFLAGS       = $(LDFLAGS_N)

#--- Debug mode options

  LIBS_D        = $(LIBS_N) -lhmd

  LDFLAGS_D     = -lessl_r -lmass -bloadmap:loadmap.txt \
                  -bdatapsize:64K -bstackpsize:64K $(OMP)

#--- Empty out mpi library definition: embedded in compiler

  LIBmpi	= 
