function (setJET)
  message("Setting paths for JET")
  set(HDF5_USE_STATIC_LIBRARIES "OFF")
  if( NOT DEFINED ENV{COREPATH} )
    set(COREPATH "/misc/whome/Michael.Lueken/nceplibs" PARENT_SCOPE )
    set(ENV{COREPATH} "/misc/whome/Michael.Lueken/nceplibs" PARENT_SCOPE )
  else()
    set(COREPATH $ENV{COREPATH} PARENT_SCOPE )
  endif()

  if( NOT DEFINED ENV{NETCDF_VER} )
    set(NETCDF_VER "3.6.3" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{BACIO_VER} )
    set(BACIO_VER "2.0.1" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{BUFR_VER} )
    set(BUFR_VER "10.2.5" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{CRTM_VER} )
    set(CRTM_VER "2.2.3" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{NEMSIO_VER} )
    set(NEMSIO_VER "2.2.1" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{SFCIO_VER} )
    set(SFCIO_VER "1.1.0" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{SIGIO_VER} )
    set(SIGIO_VER "1.0.1" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{SP_VER} )
    set(SP_VER "2.0.1" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{W3EMC_VER} )
    set(W3EMC_VER "2.0.5" PARENT_SCOPE)
  endif()
  if( NOT DEFINED ENV{W3NCO_VER} )
    set(W3NCO_VER "2.0.6" PARENT_SCOPE)
  endif()
endfunction()

