        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 31 19:35:36 2016
        MODULE FFTPACK_RFFTI1__genmod
          INTERFACE 
            SUBROUTINE FFTPACK_RFFTI1(N,WA,IFAC)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: WA(N)
              INTEGER(KIND=4) :: IFAC(15)
            END SUBROUTINE FFTPACK_RFFTI1
          END INTERFACE 
        END MODULE FFTPACK_RFFTI1__genmod
